{% set versions = {
    "1.0.0": "b02013922387cf37745487d23b271eaae257c8af76bb3cca6bbf885dd8139e74"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "nnlojet")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://nnlojet.hepforge.org/nnlojet-v{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python
    - make
    - cmake
  host:
    - python
    - llvm-openmp
  run:
    - python
    - llvm-openmp

about:
  home: "https://nnlojet.hepforge.org"
  license: "GPL-3.0"
  summary: "A parton-level event generator for jet cross sections at NNLO QCD accuracy"
  description: |
    NNLOJET is a parton-level event generator for jet cross sections using the antenna subtraction method. It can be used to compute a large number of jet cross sections and related observables in ee and pp collisions at next-to-next-to-leading order in QCD. NNLOJET contains routines for Monte Carlo phase-space integration, event handling and analysis.

extra:
  recipe-maintainers:
    - meiyasan
